### ISSUE TITLE
error alarm. Beginner's problem

### ISSUE THREAD

**Issue by cyz-001** [zeno-ml/zeno-build#122]
I don't know what to do with it. I made the following changes in the original file.I ran the code in vscode. do_prediction can work, but do_visualization can't.

I modified these hyperparameters
![image](https://github.com/zeno-ml/zeno-build/assets/53904568/227577ee-c3ae-4861-b021-3add300aa607)

![image](https://github.com/zeno-ml/zeno-build/assets/53904568/48bd157d-96f9-441c-9f61-bc2d86deafc0)
I took the l out of it and turned it into
![image](https://github.com/zeno-ml/zeno-build/assets/53904568/b4734010-5e26-4046-926b-a375b338191e)
I changed the address
![image](https://github.com/zeno-ml/zeno-build/assets/53904568/323252ec-2406-4bf6-b925-50ac98650b9b)
I added this code at the very beginning of the file
![image](https://github.com/zeno-ml/zeno-build/assets/53904568/c9732794-7128-4331-a2e2-dea01d89a55a)

The problem that appeared before no longer appears, but now the problem do not know how to solve.
![image](https://github.com/zeno-ml/zeno-build/assets/53904568/d916145b-a3b0-4b6c-a671-ea2f25ebaf20)

**Comment by cyz-001** [comment]
You all are incredible! The issue has been successfully resolved. Thank you so much for your tremendous help!

**Comment by neubig** [comment]
Great! if you run into any other trouble please ask.
