### ISSUE TITLE
GPT-MT: Add GPT-4

### ISSUE THREAD

**Issue by neubig** [zeno-ml/zeno-build#128]
Currently we don't have results for GPT-4 on the [GPT-MT report](https://github.com/zeno-ml/zeno-build/tree/main/examples/analysis_gpt_mt), but it would be nice to have them.

**Comment by hanyh** [comment]
@neubig: Thanks Graham for this amazing analysis. I hoped someone would do this analysis when we released the data, I am happy that you did this.  We will update GPT-MT report's repo with GPT-4 and latest GPT-Turbo very soon. I expect to get some of them on the repo today and the rest should follow shortly.

**Comment by neubig** [comment]
Thanks so much @hanyh , that would be really appreciated. If you could ping me and/or send a PR updating this repo with the new models ([here](https://github.com/zeno-ml/zeno-build/blob/main/examples/analysis_gpt_mt/config.py#L93)) when the new results are available that would be wonderful.

**Comment by neubig** [comment]
Thanks to @zwhe99 for sending in a PR for this! I'll be updating the report and online demo shortly.
