### ISSUE TITLE
A report on base, instruction tuned and chat tuned models for tasks 

### ISSUE THREAD

**Issue by karthik19967829** [zeno-ml/zeno-build#143]
Hi Team,
    Thank you for the great effort, it would be great if a report on base, instruction-tuned, and chat-tuned cases for a specific model like MPT or any other model for tasks can be provided to study the impact of chat and instruction tuning on tasks

**Comment by neubig** [comment]
Thanks @karthik19967829! I think that'd be quite interesting and we'd welcome contributions. We'd have to decide specifically which tasks to do this for. One potentially related issue is this one: https://github.com/zeno-ml/zeno-build/issues/142
