### ISSUE TITLE
Why use async functions here? 

### ISSUE THREAD

**Issue by krrishdholakia** [zeno-ml/zeno-build#178]
https://github.com/zeno-ml/zeno-build/blob/c8036aba0f61b238cf2662843c5514b2f583d90f/zeno_build/models/providers/openai_utils.py#L68C1-L69C1

Hey @neubig @macabdul9 ! it looks like we're awaiting an async openai call anyways - so i'm curious why use an async function here vs. just a normal function and call the `create` endpoint instead?

**Comment by neubig** [comment]
Hi @krrishdholakia , I'm not sure I fully understand the question. Could you provide an example of what you mean by editing the current code? (It would be nice if you could also run it to make sure that it works as expected.)
